version = 1

test_patterns = ["*_test.go"]

exclude_patterns = [".github/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/higker/sessionx"]

[[transformers]]
name = "gofmt"
enabled = true
