name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15


    - name: 检测依赖
      run: go mod tidy 

    - name: 测试存储
      run: go test -v --run=TestALL

    - name: 持续30秒benchmark测试
      run: go test -bench=. -benchtime=30s -run=none

#    - name: 覆盖率扫描
#      run: sh .deepsource.sh
#      env:
#        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}


    - name: 代码健康检测
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic -v



    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}